### ISSUE TITLE
CSGFaces not using an spatial index?

### ISSUE THREAD

**Issue by SpiritQuaddicted** [ericwa/Quakespasm#10]
http://www.celephais.net/board/view_thread.php?id=1&start=29906&end=29906

> The bulk of time in Q1 qbsp tools is spent is CSGFaces: it clips every brush against every other brush (i.e. an O(n^2) algorithm, so the qbsp run time will be proportional to the number of brushes squared). 

That sounds wasteful! :o

You could use a spatial index (kd-tree? octtree? Isn't BSP a spatially sorted tree itself?) to speed this up to O(log(n)) or something like that. I only know my way around 2D indexes but even just projecting the brushes' bboxes to 2D and indexing that to weed out the no-intersection candidates would help a lot I guess.

**Comment by ericwa** [comment]
Yep, that's true. The Q2 tools build a BSP and do the brush clipping through that, which is the code I was planning to migrate to and would fix the performance problem.

The bigger problem than slowness with CSGFaces is, it's an error-prone architecture (take the brushes, clip them against each other and produce faces, then build the BSP and assign the leaf content types based on the faces.) It creates bugs where the wrong content type can be assigned to a leaf: https://github.com/ericwa/ericw-tools/issues/114

**Comment by SpiritQuaddicted** [comment]
Oops, this totally was the wrong repo, sorry. Of course I meant to file in the tools repo.

Nice to hear Q2 tools have something you might be able to borrow :)
