### ISSUE TITLE
Issue with limits on Mac

### ISSUE THREAD

**Issue by dumptruckDS** [ericwa/Quakespasm#11]
This is copy and pasted from GGRC's Discord channel. Someone found an issue with limits in the DM4Jam pack. Wanted to document here.

>Hi guys, quick question. Is anybody experiencing crash when trying to save on certain maps in dm4jam, or it's just me? Namely "An Unpleasant Alcazar" by Danzadan and "Fear and Trembling" by Ionous. I'm running QuakeSpasm 0.93.1 on Mac OS. Thanks 

> If anyone interested, I found the issue. Saves strings buffers in QuakeSpasm are 512 chars long (function static const char *PR_UglyValueString (int type, eval_t *val)). The "problem" with these maps is that they use a lot of wad files, all of them are listed in "wad" field of the worldspawn entity. E.g. Ionious's map has the wad's list which is 721 chars long, here it is truncated: "C:\Worldcraft\WC\Q1tools\explorejam.wad;C:\Worldcraft\WC\Q1tools\retrorunic.wad;C:\Worldcraft\WC\Q1tools\map_jam4.wad;C:\Worldcraft\WC\id.wad;C:\Worldcraft\WC\Q1tools\retrojam2.wad;.."

**Comment by ericwa** [comment]
This should be fixed in b30141893836681e37a8482f3ae5496a5c428f8e
