### ISSUE TITLE
W_LoadWadFile: couldn't load gfx.wad

### ISSUE THREAD

**Issue by gaschka** [ericwa/Quakespasm#7]
Hello,

I recently updated QuakeSpasm on my Mac to QuakeSpasm-0.93.0-osx-SDL2, but I can't get it running. The launcher starts, but as soon I hit Start I get the following error message:
 

> **Quake Error**
> W_LoadWadFile: couldn't load gfx.wad
> Basedir is: 
> /private/var/folders/9m/xby2x0c57r7c27l28jvzss9m0000gn/T/AppTranslocation/3EAD618A-94D8-4B27-A116-98F87F6D2511/d
> Check that this has an id1 subdirectory containing pak0.pak and pak1.pak, or use the -basedir command-line option to specify another directory.

**Comment by ericwa** [comment]
Hi, this is a security feature of macOS.

Try dragging QuakeSpasm-SDL2.app onto your desktop, then drag it back to your Quake directory. This should disable "app translocation".

**Comment by gaschka** [comment]
Thanks, this helped!
